[admins]
	#Default, all Ops have access to Server Admin UI in the Options screen.
	#If set to false, only users in the Admin List will have access.
	#If set to true, all ops and users in the Admin List will have access.
	opAccess = false
	#Players in this list have access to the Journeymap's Server Admin Panel
	#Add users by name or UUID, Prefer UUID as it is more secure!
	#Each value on a new line with the example format provided. (please delete the default values)
	serverAdmins = ["ef8bd528-9cc8-47f1-8ef5-c7219f5d069b"]
